// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDior9B5w7eLz3VJ8VkDvdTsLClxarsg',
    appId: '1:924757163689:web:953e221c964b6f18b2f3b8',
    messagingSenderId: '924757163689',
    projectId: 'haedam-dd25b',
    authDomain: 'haedam-dd25b.firebaseapp.com',
    storageBucket: 'haedam-dd25b.firebasestorage.app',
    measurementId: 'G-YFT77M1BPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxDior9B5w7eLz3VJ8VkDvdTsLClxarsg',
    appId: '1:924757163689:android:your-android-app-id',
    messagingSenderId: '924757163689',
    projectId: 'haedam-dd25b',
    storageBucket: 'haedam-dd25b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxDior9B5w7eLz3VJ8VkDvdTsLClxarsg',
    appId: '1:924757163689:ios:your-ios-app-id',
    messagingSenderId: '924757163689',
    projectId: 'haedam-dd25b',
    storageBucket: 'haedam-dd25b.firebasestorage.app',
    iosBundleId: 'com.example.haedam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxDior9B5w7eLz3VJ8VkDvdTsLClxarsg',
    appId: '1:924757163689:ios:your-macos-app-id',
    messagingSenderId: '924757163689',
    projectId: 'haedam-dd25b',
    storageBucket: 'haedam-dd25b.firebasestorage.app',
    iosBundleId: 'com.example.haedam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxDior9B5w7eLz3VJ8VkDvdTsLClxarsg',
    appId: '1:924757163689:web:953e221c964b6f18b2f3b8',
    messagingSenderId: '924757163689',
    projectId: 'haedam-dd25b',
    storageBucket: 'haedam-dd25b.firebasestorage.app',
  );
}
